### ISSUE TITLE
You get a selection cursor while hovering over the 'Find your friends' h1

### ISSUE THREAD

**Issue by FredrikAugust** [NateBrune/AetherPeerDump#1]
For some strange reason you get a selection cursor while hovering over the 'Find your friends' field on the front page. This makes is look as though it is an input.

**Comment by NateBrune** [comment]
Hey man thank you so much for opening an issue. You happen to be the first person who has ever opened an issue on any of my projects ever so I hope you feel warm and fuzzy inside like I do. Thanks to you the issue has been fixed there and many other places in the website too!

**Comment by NateBrune** [comment]
I just realized I should probably keep this open for a bit in case I misunderstood the issue, which would be hilarious given my little speech above.

**Comment by FredrikAugust** [comment]
Heh, no problem. I know the feeling when some stranger actually pays attention to your project :smile:

**Comment by FredrikAugust** [comment]
Yep, you fixed the issue :)
