### ISSUE TITLE
Ping code - whoops

### ISSUE THREAD

**Issue by n17r4m** [NateBrune/AetherPeerDump#3]
I mucked up a bit in my haste. 

When reading the IP and port from the table, I forget to trim the whitespace away.

```
            $("#ptable").find("tr").each(function(){
                    var $tds = $(this).find("td");
                    if($tds.length == 4){
                            var ip = $tds[1].textContent.replace(/^\s+|\s+$/g, '')
                            var port = $tds[2].textContent.replace(/^\s+|\s+$/g, '')
                            ping("http://" + ip + ":" + port).then(function(ms){
                                    $tds[3].innerHTML = " (" + ms + ")"
                            }).catch(function(e){
                                    $tds[3].innerHTML = " (down)"
                            })
                    }
            })
```

**Comment by n17r4m** [comment]
Hope you don't mind... I went ahead and patched the live site. 

One outstanding issue is that the pings always fail for yourself, so to see if your personal node is up, you need to visit the page from a different location. :/

**Comment by NateBrune** [comment]
Yeah that is a pretty bad issue :( and no man I have no problem at all. I didnt know you where the guy hosting the server lol (thanks again!). I have to do a bit of a merge to get the actual code that is running on the server into this github repo. I actually screwed up the live site pretty bad just now and im not sure exactly what your patch was. I am working on code that deuglifies the index.php after simple_dom mucks it up.

**Comment by n17r4m** [comment]
haha, yea, that's me. lol. Any chance you'd rather just swap in MySQL?

Edit: in addition, should maybe be doing the pings server-side as well, would alleviate the issue of not seeing your own server up. sigh... all this for what ought not be needed in the first place. _shrugs_

**Comment by NateBrune** [comment]
Yeah I thought about doing it server side but then I had another thought. The ping millisecond thing is kinda useful. What is only 32 ms away from canada might be 7000ms from me. I feel like doing the ping in your browser is more responsible as long as we are including the milliseconds.

regarding mysql. _sigh_ I know I totally should swap in mysql. I feel like if my deuglifying code works though, that this method might suddenly become a lot more elegant and manageable.

**Comment by NateBrune** [comment]
right now I am dealing with another crisis. I kid you not, my computers hard drive just rolled over, clicked a couple times and died about an hour ago. I am currently on my laptop trying to update the site lol

**Comment by n17r4m** [comment]
Pings.. hmm. true enough that.

MySQL.. fair enough. not too much point pooling too much extra effort on this, since it's supposed to be a band-aid while aether gets its shit together. :) Every once in a while, should just save the export in case the data gets clobbered somehow - _shrugs_  

Dead computer.. sorry to hear! that sucks. :8ball: Good luck with getting her back on her feet!

**Comment by n17r4m** [comment]
One last thing, I'll add a note to the bottom of the page noting that the ping has the limitation that you cannot see if your own server is up from the same IP aether is running on.

**Comment by NateBrune** [comment]
I dont think I overwrote it but I might have. I don't see the footnote.

**Comment by n17r4m** [comment]
way down at the very bottom.

**Comment by NateBrune** [comment]
I see it now :+1:

**Comment by NateBrune** [comment]
Alright. I added the beautifying code that makes it readable after simple_html_dom writes the file. Now if you view source it will look like a website, not like an executable opened in notepad xD 
Does that float your boat a bit better?

**Comment by n17r4m** [comment]
Nice background! Code looks good. Boat is floating.
