### ISSUE TITLE
Woah! Are you storing the entries in an html file?

### ISSUE THREAD

**Issue by FredrikAugust** [NateBrune/AetherPeerDump#6]
Why aren't you using a database?!
In the addpeer.php site I noticed that you're just dumping the request content into the index.php file. Doesn't this make it super vulnerable to CSRF and XSS etc?

I would really recommend you moving to some sort of database! It should be really easy to implement MySQL since you're using PHP and they cooperate very well.

Feel free to contact me if you need help :smile:

**Comment by NateBrune** [comment]
Congrats! You found the ugliest hack in the repo! I sanatise everything before it gets stored but you are right, I should be using a database. With aether v2 with a revised peer finding algorithm coming soon I just didn't feel like setting up a database and this method also provided an interesting challenge. I have experience working with sql and php and I can implement it on my own but I really appreciate it. If you can provide me with a really good reason to move to a database however, I will totally do it. Sorry, I don't mean to be disrespectful, I am just lazy and I feel this website is a band-aid for a temporary problem so why bother setting up the server. Tl;dr You are right, but I am lazy.

**Comment by FredrikAugust** [comment]
Haha, ok. As long as you sanitise it it's not a big deal. The only other issue could be backup, but this works as you said. If you want to use Postgresql you could use mine if you want :)

**Comment by FredrikAugust** [comment]
All entries on [this](http://rocky-refuge-6432.herokuapp.com/) site is stored in a database so far, and I'm keeping it live updated with yours and vice-versa.
